### ISSUE TITLE
문제점 정의!

### ISSUE THREAD

**Issue by Hyunsu1227** [Real-Time-Video-Processing/Real-Time-Video-Processing#1]
핸드폰, 웨어러블 카메라 (이동 가능한 머신) 에서 영상을 전송하면 -> 다른 화면에서 실시간으로 영상을 볼 수 있다.

키워드 : 사회안전, 드론, 머신러닝, 영상 효율적 전송, VR

이것을 통해 우리가 해결할 수 있는 문제를 정의합시다.

**Comment by ljh7857** [comment]
심박/혈압 등 건강정보 연계 전송
건강정보에 이상이 있을 때 구급대원이 출동하는 등의 서비스는 있지만
센서가 잘못 측정하는 등의 오작동이 있을 수 있기 때문에 잘못 출동하는 것을 방지할 수 있습니다.
또한 환자의 더욱 자세한 상황을 파악할 수 있습니다.

**Comment by jobgunwiz** [comment]
드론 상호 연결 전송 체계
드론은 컨트롤러의 신호 범위에서 벗어나면 작동 불능 상태가 됩니다. 동굴이나 지하처럼 신호 간섭이 심한 곳에서는 더 짧은 거리까지만 전파가 도달합니다. 드론을 뱀처럼 무선 연결하면 각자가 신호 중계기 역할을 함으로써 선두의 드론을 원하는 곳 까지 이동시키고, 나아가 해당 드론이 전송하는 영상을 실시간으로 얻을 수 있습니다.
산악지대 조난, 동굴에서 실종 또는 해상 조난 사태 발생시 별도의 통신망 없이도 더 넓은 범위를 효과적으로 탐색할 수 있을 것입니다.

**Comment by oms801** [comment]
영상 전송 최적화
저화질에서도 상황 판단이 충분히 가능한 긴급상황의 경우(산불, 건강상태 등) 
실시간 영상 정보를 바로 바로 얻어 현장상황을 파악해야 하는데(산불 규모, 환자 움직임 여부)
전파가 약해져서 동영상이 버퍼링이 걸리게 되면 정확한 현장 대응을 하기 어려워집니다.
-> 문제점 : 동영상 지연 때문에, 긴급상황에 대한 적절하고 빠른 대처가 어려워 질 수 있다. 
-> 이를 해결하기 위해 버퍼링을 하지않고 전파강도에 맞는 최적화된 동영상 시스템으로 계속 바꿔주는 기술이 필요하다고 생각합니다.

**Comment by justinjoy** [comment]
늦게까지 고생 많았습니다. 
최종 합의된 내용으로 정리를 해주시면 몇가지 요소를 고려하여  #3 으로 넘어가보도록 하는게 좋겠습니다.

**Comment by JaeyoonCheon** [comment]
영상 전송 최적화, 심박/혈압 등 건강정보 연계 전송

웨어러블, 센서로 인식된 응급 상황 발생 시 환자가 의식이 없다면 환자의 상황을 바로 알 수 없기 때문에 응급 조치가 힘들다는 문제점이 발생합니다.
환자가 의식이 없어도 주변 사람들이 응급 조치를 할 수 있도록 자동으로 실시간 영상을 관제 센터 등으로 전송, 중계 할 수 있다면 긴급한 상황에 대처할 수 있을 것이라고 생각합니다.

**Comment by justinjoy** [comment]
게시된 항목들의 공통된 내용으로 정리 해본다면 저는 이렇게 생각이 됩니다.

  * 목표: 영상을 통한 상황인지
  * 어려운점: 네트워크 대역폭 확보의 어려움이 발생

이러한 관점으로 볼때, "어려운점"을 해결했을 때 가장 효과적인 적용 사례가 무엇이 될지 결정하는 것이 좋겠습니다.

**Comment by oms801** [comment]
네트워크 대역폭이 확보가 되면, 지연이 적어져서 
거의 실시간으로 상황 파악이 가능할 것이라고 생각합니다. 
재난상황이나 인명구조 같은 긴급상황에서 
영상을 전달받는 사람들이 실시간으로 출동인원, 현장 주변인들에게 정보를 줄 수 있습니다.
이를 통해 이 인원들이 상황에 맞는 대처를 계획하고 수정하는데 도움이 될 것이라고 생각합니다.
-> 정리 : 긴급 상황 발생 시 빠른 상황인지를 통해 상황에 맞는 대처 계획 및 수정이 가능하다.

**Comment by ansehdwls** [comment]
실시간 영상 전송의 최적화
문제점 : 위급 상황이나 다급한 산재상황일때 실시간으로 바로 연락할 수있는 플렛폼의 부족.
실제 사고나 상황이 일어났을때 장소 위치를 정확하게 알 수 없고 실시간영상으로 전달할 수있는 방법도 적다고 생각합니다.
일반인의 입장으로 처음가는길 도로중간에 산사태가 일어나서 지인이 다쳐 응급상황일때 119에 전화 하고 간단한 응급처치라든가 도로 및 교통 정리 상황이 힘들거라 판단됩니다. 
해결: 문제 상황이 일어날시 휴대폰 버튼하나로 주변의 119와 112 등의 해결기관으로 실시간 영상을 동시에 보내어 빠르게 상황을 인지 및 판단하고 각 처소에서 해당된 문제 상황을 분할하여 해결할 수 있도록 할 수 있는 플렛폼의 개발.
네크워크전파망의 해결도 하나의 해결방안이겠지만 어떻게하면 더 빠르게 전송할 수있을까 전송 시작지점을 빠르게 하면 어떨까 하는 생각에서 이런생각이 들었습니다.

**Comment by justinjoy** [comment]
그렇다면 _누구_ 의 문제를 해결하는 것이 프로젝트에서 집중할 부분인가요? 

 1. 위급 상황에 처한 사람 (영상 송출)
 1. 영상을 획득한 사람의 빠른 의사 결정 (영상 수신)
 1. ??

**Comment by krwns97** [comment]
아무래도 위급사항 발생시  전문 기관이나 사람에게  영상을 빠르게 송출하는 부분이 중요하지 않을까 생각됩니다.

**Comment by justinjoy** [comment]
한번더 정리해보았습니다.

  - 목표: 영상을 통한 상황인지에 대한 기여
  - 어려운점:  ~~네트워크 대역폭 확보의 어려움이 발생~~
    - 상황을 최초에 인지한 사람(혹은 객체)에서 즉각적인 영상 송출의 어려움
  - 적용 가능 시나리오
    - 인명 구조
    - 산불 감시

**Comment by krwns97** [comment]
빠른 시간안에 영상을 119나 전문기관에게 알려 그들이 빠른 상황 판단을 할 수 있도록 하는것으로
가장 큰 이익을 보는 사례를 중점으로 생각해보았습니다.
문제 : 산불발생시 빠르게 인지하지 못해 초기진압에 실패하여 피해가 더 커진 경우가 많습니다.
해결 : 건조주의보등 산불 발생할 확률이 높은 기간에 드론을 띄어 산불이 발생되었을때 빠르게 관련 기관에 발생 위치 및 정보를 전달하면 해결되지 않을까 생각됩니다.

**Comment by krwns97** [comment]
인명 구조에 관련하여 생각해본 사례입니다.
문제 : 교통사고 발생시 운전자가 기절을 하거나 빠른 상황판단을 하지 못하여 빠른 대처를 못하는 경우가 있습니다.
이는 다중 추돌사고등 더 큰 사고로 이어질수도 있습니다.
해결 : 사고발생시 블랙박스 영상 및 위치등을 자동으로 보험사 및 구조센터,각 기관에 전달하여 빠른 판단을 할수 있도록 도와주면 재난문자를 보낸다거나, 고속도로 순찰대를 빠르게 파견하는등 더 큰 사고를 막을 수 있지 않을까 생각됩니다.

**Comment by ansehdwls** [comment]
스마트 영상 응급처치는 시 소방재난본부 측에서 신고자에게 영상통화를 거는 방식이다.

사례) 신고자가 스마트폰을 가지고 있는 경우, 영상통화를 통해 
        실시간으로 현장을 확인하며 올바른 응급처치를 알려주는 서비스다.
        시 소방재난본부는 "심정지 환자의 경우 골든타임은 4분이지만 
        복잡한 도로 사정 등으로 구급차 현장 도착이 늦어지는 때가 종종 있다"며 
        "실시간으로 적절한 처치를 할 수 있고, 현장 정보가 구급지도 의사와 
        출동 중인 구급대에도 바로 전달되는 효과가 있다"고 소개했다.
       실제로 시 소방재난본부가 지난 3개월간 시범 운영한 결과, 
       시민의 응급처치 질이 향상돼 골든타임 내 적절한 대처를 하는 사례가 늘어났다.

실제 소방서에서 사용 하는 실시간 응급처치 관련 사례인데 신고자측에서 송출할수 있는 시스템이 아니다 보니
상황을 최초에 인지한 신고자측에서 즉각적으로 송출할 방법을 고안한다면 더빠른 응급처치가 가능할것같습니다

**Comment by justinjoy** [comment]
개선하고자 하는 구체적인 시나리오는 #4 에서 다루기로 하고, 본 이슈에서는 **프로젝트의 목표**를 결정하고 마무리 짓도록 하는 편이 좋겠습니다.
지금까지 나열된 내용을 정리하면 발표자료 1~2페이지 정도의 목표 설정을 기술 할 수 있을 것으로 보입니다.

최종 안으로  정리하여 주세요.

**Comment by ansehdwls** [comment]
최종안 입니다.
주제 : 영상을 통한 빠른 신고 체계 수립 

문제점 : 1. 사람이 없는 장소에서 위급한 상황이 발생했을 때 누군가가 상황을 파악해 소방서 등에
	 신고하기에는 어려움 있음 ex) 산불
            2. 도로에서의 사고가 일어나 경황이 없어 패닉이 일어났을때 전화로만은 정확한 상황전달이
	 불가능하여 상황에 알맞은 대처가 늦어짐.
            3. 문자나 소리로의 전달은 한계가 있음.
	 ex) 풍속 18m/s , 강수량 110mm의 비가 영남 지방에 내림 
	     -> 예측은 되지만 현상황을 알기엔 부족한점이있음.
            4. 1인 가정의 경우 긴급한 상황이 발생했을 때 사고를 발견하고 조치를 취하기엔 어려움이 
	많다.

영상을 통한 빠른 신고 체계가 필요한 이유 : 
1. 정확하지 못한 신고 전달으로 빠른대처가 늦어질 수 있음.
2. 영상을 통한 신고가 보다 정확한 진단을 내리기에 유용.
3. 영상전달으로 인한 상황 전달이 음성신고 보다 상황인지가 빠름.
4. 인적이 드문 장소에서 위급한 상황 발생시 영상을 통한 정확하고 빠른인지.
5. 동시적인 영상 전달으로 위험지역의 사람들이 쉽게 상황을 인지 할 수 있다.
6. 사고 발생시 빠른 영상 전달으로 위급상황이 발생할 수 있는 지인들의 걱정을 덜 수 있다.

**Comment by justinjoy** [comment]
전체적인 맥락은 훌륭합니다만 하나 피드백을 드리자면 **문제점** 부분이 사용자 **시나리오** 와 구분이 잘 안되는 부분이 있습니다.

기술한 내용으로 구분하자면, 

> 영상을 통한 빠른 신고 체계가 필요한 이유:

위 항목이 우리가 해결하는 문제 (Problem definition)이고 

> 문제점:

위 부분은 응용 가능한 영역에 대한 정의 (Use Case)가 됩니다.

이런 관점에서 본다면 우리 프로젝트는  __영상으로 신속한 상황을 전달하고자 할때 발생하는 문제를 극복__ 하는 것이 되겠네요.
이렇게 종합해서 발표자료를 만드시면 훌륭한 자료가 나올것 같습니다.

수고하셨습니다. 

더 논의 할 내용이 있으면, 코멘트를 달아주시고 종료해도 되겠다 싶으면 이슈를 Close  해주세요.
