### ISSUE TITLE
0924 회의록

### ISSUE THREAD

**Issue by ljh7857** [Real-Time-Video-Processing/Real-time-video-processing#11]
11월 2일 중간발표 (데모 영상까지)
4주정도 있으니 매 주마다 마일스톤 세워서. 애자일 스프린트
정기적으로 진행상황 체크하자 -> 화 일 10분씩 상황 공유중
개울 라이브러리 어렵다 : 
오픈소스 3 질문 : 왜 공유하나? 왜 돈 내나? ...
타인이 자신의 상업 서비스에 쉽게 이용하는 것을 방지하려고 의도적으로 어렵게 했다.
sk 드론 촬영, 관제 시연 영상.
드론 수동 조종 전환 지연시간
인천공항 순찰 로봇
오픈소스 정신 위배하는 것 아니냐??
: 오피셜과 언오피셜의 차이.
생태계를 만들어서 돈을 벌자.
LGPL 라이센스, 아파치 라이센스

영상 전송에 집중하는지? 엔드 투 엔드로 할건지??
엔드투엔드는 있는거 다 써야함.
VLC나 RTSP 플레이어??
지금쯤 뭘 어떻게 할지 확실히 정해져야 한다.
논문 시스템 구성도 놓고 설명하는게 반일것.
만약 일부만 한다면 전체를 두고 이 부분이 가장 중요한 이유를 잘 포장하면 됨.
미디어 서버 같은 이미 있는 서비스가 있다면 영상 전송에만 집중하면 된다.
일부를 먼저 하고 나중에 확장하는 방식으로 나아갈 수 있다.

지금처럼 딱딱 나눠서 하는것은 협업이라는 프로젝트의 취지와 맞지않는 것 같다.
차라리 범위를 줄이고 다 같이 하는 것은 어떻겠나?
논문은 전체를 다루고 프젝은 그 일부를 구현하는 것.

다음 회의 안건을 이슈에 올리자.
다음주 추석은 회의는 쉬고 이슈를 활용하는 것으로.

혹시 추가할 것이나 정정할 것 있으시면 적어주시면 감사하겠습니다.
+언어 순화 했습니다 ㅎㅎ;

**Comment by justinjoy** [comment]
> 날먹 방지... 

:sweat_smile:
