### ISSUE TITLE
문제 해결을 위한 시나리오 찾기

### ISSUE THREAD

**Issue by justinjoy** [Real-Time-Video-Processing/Real-time-video-processing#4]
#1 에서 정의한 문제를 해결하였을때 가장 효과적인 시나리오는 무엇인가요?

현재까지 알려진 방안과 비교하여 프로젝트에서 제시할 수 있는 개선 혹은 강점을 표현하는 것을 중심으로 2개 정도의 시나리오를 확정해야합니다.

**Comment by ljh7857** [comment]
시나리오 후보

1. 재난감시시스템 (산불 등)
2. 웨어러블과 연계한 1인가구 cctv
3. 블랙박스 등을 활용한 교통사고 영상 전송
4. 신고자가 소방서에 영상을 전송해 응급처치 수행

다음과 같이 정리해 보았습니다. 혹시 더 추가하고 싶은 시나리오가 있으면 적어주세요
+@ 5. 해상에서 드론을 통해 NLL침범이나 중국어선의 불법조업을 단속

**Comment by Hyunsu1227** [comment]
1. 불이 날 수 있는 장소에 무인 카메라가 불을 감시하고 있다. 그래서 만약 불이 난다면 카메라가 이를 감지하고 관리자에게 이를 알린다. 이후 관리자가 카메라를 통해 실시간으로 영상을 전달받고 조기 대처한다. 

2. 집에 나이 든 부모님이 혼자 계실 때 팔찌나 웨어러블을 통해 넘어질 때 , 체온, 맥박 등 을 감지해 위급한 상황이 발생된 경우 시스템 사용자에게 알림이 가고 그 이후 영상을 확인해 빠른 상황판단 및 대처

3. 차량 다중 추돌사고등 큰 차량사고 발생시 운전자 및 동승자가 기절하는등 신고가 늦어질 가능성이 농후, 이 때 블랙박스가 자동으로 사고를 감지해 각 보험사,119등 빠르게 신고 및 영상전송으로 빠른 상황 판단 및 대처

4. 사고가 발생할 때 응급한 환자 등이 발견됐는데 대처법을 잘 모를 때 소방서와 영상 전송을 통해 응급 상황을 대처하고 소방서 등도 사고현장에 대한 정확한 상황 인지

5. NLL인근이나 불법 중국 어선이 자주 넘나드는 서해에 드론을띄어 상시 감시를 한다. 만약 선박의 침입이 감지되는 경우 해경 혹은 군에 빠른 영상전송으로 조기 대처가 가능하게 한다.

**Comment by ljh7857** [comment]
투표 결과 3번 시나리오로 결정되었습니다.

**Comment by justinjoy** [comment]
시나리오가 선정 되었기에 본 이슈는 종료 합니다.
